apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-ci-cd-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: practica-ci-cd
      version: green
  template:
    metadata:
      labels:
        app: practica-ci-cd
        version: green
    spec:
      containers:
      - name: app
        image: ghcr.io/alejandr05ang/practica-ci-cd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000