apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-ci-cd-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: practica-ci-cd
      version: green
  template:
    metadata:
      labels:
        app: practica-ci-cd
        version: green
    spec:
      containers:
      - name: app
        image: ghcr.io/alejandr05ang/b96bef9e64671c87f2d3440ba25f76e7b2f5580c:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        - name: APP_VERSION
          value: "v2"
        - name: APP_COLOR
          value: "green"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000