apiVersion: v1
kind: Service
metadata:
  name: inventario-service
spec:
  type: NodePort
  selector:
    app: practica-ci-cd
    #version: green
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081